3Hren/cocaine-core

- debian/changelog
- include/cocaine/detail/service/node/app.hpp
- src/service/node/app.cpp
Prevent working with nullptr engine and deleted app_t from app_service_t during application stop
> Application race fix

- CMakeLists.txt
- debian/changelog
- include/cocaine/api/isolate.hpp
- include/cocaine/detail/isolate/process.hpp
- include/cocaine/detail/service/node/slave.hpp
- include/cocaine/detail/service/node/slave/state/spawning.hpp
- include/cocaine/detail/service/node/slave/state/stopped.hpp
- src/isolate/process.cpp
- src/runtime/runtime.cpp
- src/service/node/app.cpp
- src/service/node/slave.cpp
- src/service/node/slave/state/spawning.cpp
- src/service/node/slave/state/stopped.cpp
May be not ideal solution, but I was unable to develop the better one.
> [Process] Collecting zombies.

- include/cocaine/detail/service/node/slave/state/state.hpp
- include/cocaine/detail/service/node/slave/state/terminating.hpp
- src/service/node/slave.cpp
- src/service/node/slave/state/state.cpp
- src/service/node/slave/state/terminating.cpp
> [Fix] Do not write crashlog if slave is terminating at the moment.

- include/cocaine/hpack/header.hpp
- include/cocaine/hpack/msgpack_traits.hpp
- include/cocaine/rpc/asio/decoder.hpp
- include/cocaine/rpc/asio/encoder.hpp
- include/cocaine/rpc/asio/readable_stream.hpp
- src/header.cpp
- tests/unit/header_table.cpp
This PR enables zipkin itself and fixes several logic errors in headers
> [Fix] Fix header_table_t::size behaviour. Add zipkin packing.

- include/cocaine/hpack/header.hpp
- include/cocaine/rpc/asio/decoder.hpp
- include/cocaine/trace/stack_string.hpp
- include/cocaine/trace/trace.hpp
- include/cocaine/trace/trace_impl.hpp
- src/session.cpp
> Headers fix

- include/cocaine/errors.hpp
- include/cocaine/hpack/msgpack_traits.hpp
- include/cocaine/rpc/asio/decoder.hpp
- include/cocaine/rpc/asio/encoder.hpp
- include/cocaine/rpc/asio/writable_stream.hpp
- include/cocaine/rpc/session.hpp
- include/cocaine/rpc/upstream.hpp
- src/session.cpp
cherry-picked from cocaine/cocaine-core
> [RPC] HPACK refactoring.

- debian/changelog
- include/cocaine/rpc/asio/encoder.hpp
- include/cocaine/rpc/asio/writable_stream.hpp
> [Fix] Extend lifetime of encoded message in writable buffer.

- include/cocaine/detail/service/locator.hpp
- src/service/locator.cpp
subj. Post to event loop would also require lock, so I've just only put lock in connection_sink.
> [Fix] Aquire lock during protocol cleanup.

- include/cocaine/hpack/msgpack_traits.hpp
> [Hpack] 3d value can not be integer. Only raw.

- src/actor.cpp
- src/actor_unix.cpp
- src/engine.cpp
> style(logs): consistency for logging prefixes

- src/trace.cpp
> fix(zipkin): initialize was_pushed in trace ctor

- src/engine.cpp
Enabling keep alive for TCP socket is required to avoid weird IPVS behavior
on erasing a table record, which lead to infinite socket consuming and making
us suffer from fd leakage.
Note, that there is another solution: with reading `null_buffers` every N
seconds we can check an error code received.
> feat(engine): enable TCP keep alive option

- CMakeLists.txt
- include/cocaine/api/unicorn.hpp
- include/cocaine/errors.hpp
- include/cocaine/unicorn/path.hpp
- include/cocaine/unicorn/value.hpp
- include/cocaine/unicorn/writable.hpp
- src/api.cpp
- src/errors.cpp
- src/signal.cpp
- src/unicorn/value.cpp
Moved it as is.
Give me a second to apply cocaine-core code style.
> feat(unicorn): api is a part of cocaine now

- include/cocaine/hpack/header.hpp
- src/header.cpp
> feat(hpack): improve headers storage API

- debian/changelog
- include/cocaine/logging.hpp
- src/runtime/runtime.cpp
- src/service/logging.cpp
- src/session.cpp
> Tracing logs as debug

- CMakeLists.txt
- include/cocaine/context.hpp
- include/cocaine/context/config.hpp
- src/actor.cpp
- src/api.cpp
- src/context.cpp
- src/context/config.cpp
- src/context/mapper.cpp
- src/runtime/runtime.cpp
- src/service/logging.cpp
Config is interface now. 
That helps to maintain compatibility and also reduces compile time.
> Config interface

- include/cocaine/context.hpp
- include/cocaine/context/filter.hpp
- include/cocaine/detail/trace/logger.hpp
- include/cocaine/forwards.hpp
- src/context.cpp
- src/runtime/runtime.cpp
- src/trace/logger.cpp
subj. This is needed for runtime filtering change in upcoming new logging service.
> refactor(context): provide custom filter capability

- debian/changelog
- include/cocaine/errors.hpp
- src/errors.cpp
> Fix registrar initialization

- CMakeLists.txt
- debian/control
- debian/libcocaine-dev.install
- debian/libcocaine-dev.links
- debian/libcocaine-io-util3.install
> Shared util lib

- src/errors.cpp
> fix(error_categories): really map by name, not by pointer

- include/cocaine/rpc/slot/streamed.hpp
- include/cocaine/utility/exchange.hpp
> feat: streamed<T> now throws if it was closed

- include/cocaine/context.hpp
- include/cocaine/repository.hpp
- src/context.cpp
- src/runtime/runtime.cpp
new PR without serious API breakage (instead of https://github.com/3Hren/cocaine-core/pull/96)
> Statefull factory

- CMakeLists.txt
- include/cocaine/api/storage.hpp
- include/cocaine/detail/storage/files.hpp
- include/cocaine/utility/future.hpp
- src/api/storage.cpp
- src/crypto.cpp
- src/runtime/runtime.cpp
- src/service/locator.cpp
- src/service/storage.cpp
- src/storage/files.cpp
> refact(): storage now provides async operations.

- include/cocaine/dynamic/converters.hpp
> fix: check whether all values are convertible
