3Hren/cocaine-core

debian/control, debian/rules
cocaine-runtime now is a virtual package.
=> Separate package for cocaine v12.

include/cocaine/detail/service/node/slave.hpp, src/service/node/app.cpp, src/service/node/engine.cpp, src/service/node/slave.cpp
When pool was cleared before engine_t::activate was dispatched by loop
activate was performed on invalid pointer. Also sending errors during
engine_t::migrate and app_t::enqueue to disconnected client lead to
uncaught exceptions. This patch should fix this.
=> [Bug Fix] Fix race in engine_t and uncaught exception in app_t.

include/cocaine/api/isolate.hpp, include/cocaine/detail/isolate/process.hpp, src/isolate/process/spooler.cpp, src/service/node/app.cpp
New method: `async_spool`.
Tries to spool an application non-blocking way (if possible).
=> Preserve default spool.

include/cocaine/rpc/asio/header.hpp, tests/unit/header_table.cpp
This behaviour is redundant and inconsistent. Now header is not changed
to point to data in the header table during push.
=> [Headers] Do not change header while pushing to header table.

debian/cocaine-v12-runtime.init
A folder with Cocaine defaults has changed its name from `/etc/default/cocaine-runtime` to `/etc/default/cocaine-v12-runtime` since `v0.12`. The new path wasn't updated in the init script, causing troubles during the startup. This little fix solves the problem.
=> Updated Cocaine name in the init script for 0.12 version.

include/cocaine/hpack/header.h, include/cocaine/hpack/header.hpp, include/cocaine/trace/trace_impl.hpp, src/header.cpp
This fixes assertion on trace_t::push_scope_t instantiation on empty current trace.
=> [Fix] Do not push trace scope if current scope is empty.

src/service/locator.cpp, src/service/locator/routing.cpp
invalid now. Both of them make no sense from the routing point.
Also it fixes a bug with division by zero (Zero weight group) and a bug with dereferencing of NULL pointer if a group is empty.
=> [Continuum] Empty groups and groups with zero total weights are

src/session.cpp
This one
```
[E]: uncaught invocation exception: [22] Invalid trace parameters: 16622038451144834360 16622038451144834360 0: Invalid argument ...
[E]: uncaught invocation exception: [22] Invalid trace parameters: 16622038451144834360 16622038451144834360 0: Invalid argument
```
seems more useful, than
```
[E]: uncaught invocation exception: [22] Invalid argument 
```
=> [Logs] Log e.what()

include/cocaine/trace/trace.hpp, src/trace.cpp
Do not use optional is it is not movable in old versions of boost which
leads to wrapped handler being also non-movable.
=> [Zipkin] Do not limit values of zipkin traces. Remove optional.

debian/changelog, src/actor_unix.cpp
From `app` to `service` just like in TCP actor.
@antmat TAL
=> misc(actor): changed prototype key name

.gitignore, CMakeLists.txt, include/cocaine/context.hpp, include/cocaine/context/signal.hpp, include/cocaine/idl/context.hpp, include/cocaine/signal.hpp, include/cocaine/traits/siginfo.hpp, src/actor_unix.cpp, src/runtime/logging.cpp, src/runtime/runtime.cpp, src/signal.cpp
Add safe synchronous signal handler.
Pass os signals to context signaling hub.
Use SIGHUP to reopen logger.
fix(signal_handling): misprint "shutdown" -> "os_signals"
fix(signal_handling): replace async_wait* with templated async_wait.
fix(signal_handling): remove copypaste
refactor(signal_handling): drop default action support
fix(build): build for trusty
fix(build): add missing include header
adopted new BH for signal handling
=> feat(signal handling): safe posix signal handling

src/runtime/runtime.cpp
Now wrapper in sighandler can point to already destroyed wrapper in context and cause crash on context termination.
This commit fixes this.
=> fix(segfault): use longer living logger in sighandler

include/cocaine/rpc/protocol.hpp
This fixes unicorn build (in unicorn protocol.hpp is first include, so uint64_t is undefined without this fix)
=> fix(include): add missing include

debian/cocaine-runtime.conf, include/cocaine/context/config.hpp, include/cocaine/repository.hpp, src/context/config.cpp, src/repository.cpp
Several plugin paths can be specified now, in this case 'paths.plugins' should be array of strings. Old config is also supported.
=> feat(config): several plugin paths can be specified now

include/cocaine/errors.hpp, src/errors.cpp
subj. This is needed because std::hash can differ on different platforms and we need consistency in category ids
=> refactor(errors): use well defined algo for hashing instead of std::hash

include/cocaine/traits/attributes.hpp, src/context.cpp, src/errors.cpp
fix bugs:
* Add missing generic category in registrar map
* Implicitly unregister context_filter in terminate() as function can refer to unloadable plugin, which will cause crash.
* add missing includes to traits
=> Add generic category

debian/changelog, src/errors.cpp
Subj. This is needed if we create more than one context_t instance in the same process.
=> Do not throw on duplicate category insertion if they are really the same

debian/cocaine-v12-runtime.default, debian/cocaine-v12-runtime.init, debian/rules
* Disable cocaine start by default, as it do require additional setup (f.e. plugin install, configuration, etc), and force the user to explicitly enable it in /etc/default/cocaine-v12-runtime
Also this fixes the problem with alternative startup tool usage.
* Parallel build in debianization to speed up compilation
=> Debianization fix

include/cocaine/context.hpp, src/runtime/runtime.cpp
subj. This also leads to corruption due to second call to 'terminate' during destruction
=> refactor(context): drop useless and senseless terminate method

include/cocaine/errors.hpp, include/cocaine/repository.hpp, src/errors.cpp, src/repository.cpp
It provides better error messages and do not add extra dependencies
=> refact(dlopen): use simple dlopen instead of ltdl 

include/cocaine/api/service.hpp, include/cocaine/context/signal.hpp, include/cocaine/detail/service/locator.hpp, include/cocaine/detail/service/logging.hpp, include/cocaine/detail/service/storage.hpp, include/cocaine/forwards.hpp, include/cocaine/rpc/basic_dispatch.hpp, include/cocaine/rpc/dispatch.hpp, include/cocaine/rpc/slot.hpp, include/cocaine/rpc/slot/blocking.hpp, include/cocaine/rpc/slot/deferred.hpp, src/actor.cpp, src/dispatch.cpp, src/service/locator.cpp, src/service/logging.cpp, src/service/storage.cpp
- No longer keep dispatch as const. It should mutate its state,
otherwise it’s useless!
- Drop `const` from prototypes.
- Drop `const` from `dispatch::process` and `dispatch::discard`.
=> refactor: drop constness from dispatch
